apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: k-s-skaffold-hanson
build:
  artifacts:
  - image: skaffold-example
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-*.yaml
